
-- 거래처
CREATE TABLE CUSTOMERS(
	CUSTOMER_NUM INT AUTO_INCREMENT PRIMARY KEY
	, CUSTOMER_NAME VARCHAR(100) NOT NULL UNIQUE
	, CUSTOMER_ADDR VARCHAR(200) NOT NULL
	, CUSTOMER_TEL VARCHAR(50) NOT NULL
	, CUSTOMER_EMAIL VARCHAR(50) UNIQUE
);

-- 카테고리
CREATE TABLE CATEGORY(
	CATE_NUM INT AUTO_INCREMENT PRIMARY KEY
	, CATE_NAME VARCHAR(100) NOT NULL UNIQUE
);

-- 상품정보
CREATE TABLE PRODUCTS(
	PRODUCT_NUM INT AUTO_INCREMENT PRIMARY KEY
	, PRODUCT_NAME VARCHAR(100) NOT NULL 
	, CATE_NUM INT REFERENCES CATEGORY(CATE_NUM) 
	, PRODUCT_PRICE INT NOT NULL
	, STOCK INT NOT NULL 
	, DETAILE VARCHAR(300)
);

-- 발주
CREATE TABLE ORDER_REQUESTS(
 REQUEST_NUM INT AUTO_INCREMENT PRIMARY KEY
 , PRODUCT_NUM INT REFERENCES PRODUCTS(PRODUCT_NUM)
 , CUSTOMER_NUM INT REFERENCES CUSTOMERS(CUSTOMER_NUM)
 , QUANTITY INT NOT NULL
 , REQUEST_STATUS ENUM('Pending', 'Completed', 'Cancelled') NOT NULL DEFAULT 'Pending'
 , REQUEST_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
);


-- 결제
CREATE TABLE PAYMENTS(
 PAYMENT_NUM INT AUTO_INCREMENT PRIMARY KEY
 , REQUEST_NUM INT REFERENCES ORDER_REQUESTS(REQUEST_NUM)
 , PAYMENT_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
 , AMOUNT INT NOT NULL 
 , PAYMENT_METHOD VARCHAR(100) NOT NULL 
 , PAYMENT_STATUS ENUM('Pending', 'Completed', 'Failed') NOT NULL DEFAULT 'Pending'

-- 수주 테이블
CREATE TABLE ORDERS(
 ORDER_NUM INT AUTO_INCREMENT PRIMARY KEY
 , REQUEST_NUM INT REFERENCES ORDER_REQUESTS(REQUEST_NUM)
 , ORDER_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
 , ORDER_STATUS ENUM('Pending', 'Shipped', 'Delivered', 'Cancelled') NOT NULL DEFAULT 'Pending'
);