
CREATE TABLE CAR_INFO(
	MODEL_NUM INT AUTO_INCREMENT PRIMARY KEY
	, MODEL_NAME VARCHAR(20) NOT NULL
	, PRICE INT NOT NULL
	, BRAND VARCHAR(20) NOT NULL
);

DROP TABLE SALES_INFO;

CREATE TABLE SALES_INFO(
	SALES_NUM INT AUTO_INCREMENT PRIMARY KEY
	,BUYER VARCHAR(15) NOT NULL
	,BUYER_TEL VARCHAR(20) 
	,COLOR VARCHAR(10) NOT NULL
	,MODEL_NUM INT NOT NULL REFERENCES CAR_INFO(MODEL_NUM)
	,S_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
);

SELECT * FROM CAR_INFO;
SELECT * FROM SALES_INFO;

DELETE FROM car_info;
DELETE FROM car_info WHERE MODEL_NUM = 7;

INSERT INTO
sales_info(
  BUYER
  ,BUYER_TEL
  ,COLOR
  ,MODEL_NUM
  ) VALUES(
  '김석진'
  ,'010-111-1111'
  ,'화이트'
  ,6
  );
  
  SELECT 
  C.MODEL_NAME
  ,C.PRICE
  FROM car_info C, sales_info S
  WHERE C.MODEL_NUM = S.MODEL_NUM;
  
  SELECT
  BUYER
  , BUYER_TEL
  , S_DATE
  , COLOR
  , C.MODEL_NAME
  , C.PRICE
  FROM car_info C, sales_info S
  WHERE C.MODEL_NUM = S.MODEL_NUM;
  
DELETE FROM sales_info WHERE SALES_NUM = 4;