
-- 리액트 기본 게시판 프로젝트 1
-- 글번호의 AUTO_INCREMENT 는 자동_증가!!!
-- 날짜 DEFAULT (데이터를 넣지 않아도 어느 특정값을 넣어준다라는 의미
-- CURRENT_TIMESTAMP 괄호빼기 (현재 시각 스탬프!) 
CREATE TABLE REACT_BOARD(
 BOARD_NUM INT AUTO_INCREMENT PRIMARY KEY
 , BOARD_TITLE VARCHAR(50) NOT NULL
 , BOARD_CONTENT VARCHAR(100) 
 , BOARD_WRITER VARCHAR(30) NOT NULL
 , BOARD_DATE DATETIME DEFAULT CURRENT_TIMESTAMP  
);


SELECT * FROM REACT_BOARD;

INSERT INTO REACT_BOARD (
BOARD_TITLE
, BOARD_WRITER
) 
VALUES (
'아이스크림'
, '초코맛'
);



