CREATE TABLE REACT_STUDENT (
	STU_NUM INT AUTO_INCREMENT PRIMARY KEY
	, STU_NAME VARCHAR(30) NOT NULL
	, KOR_SCORE INT
	, ENG_SCORE INT
	, MATH_SCORE INT
	, STU_AGE INT 
	, STU_TEL VARCHAR(20) UNIQUE -- UNIQUE :중복 불가 
	, STU_ADDR VARCHAR(50)
);

SELECT * FROM REACT_STUDENT;

SELECT
STU_NUM
,STU_NAME
,KOR_SCORE
,ENG_SCORE
,MATH_SCORE
FROM REACT_STUDENT

INSERT INTO REACT_STUDENT (
STU_NAME
) 
VALUES (
'김남준'
);