
CREATE TABLE SCORE_INFO (
	STU_NUM INT PRIMARY KEY
	, STU_NAME VARCHAR(50)
	, KOR_SCORE INT
	, ENG_SCORE INT
	, INTRO VARCHAR(100)
);

SELECT * FROM SCORE_INFO;

DELETE FROM SCORE_INFO
WHERE STU_NUM = 1 ;

DELETE FROM SCORE_INFO
WHERE STU_NUM = 2 ;

DELETE FROM SCORE_INFO
WHERE STU_NUM = 1 ;

UPDATE score_info
SET 
STU_NAME = '김남준'
, KOR_SCORE = 100
WHERE
STU_NUM = 1;