

CREATE TABLE PRACTICE_BOARD(
	p_NUM INT AUTO_INCREMENT PRIMARY KEY 
	, TITLE VARCHAR(50) NOT NULL
	, WRITER VARCHAR(50) NOT NULL
	, CONTENT VARCHAR(100)
	, P_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
	, READ_CNT INT DEFAULT 0
);

SELECT * FROM PRACTICE_BOARD;

INSERT INTO PRACTICE_BOARD(
	TITLE ,WRITER ,CONTENT
) VALUES(
'TEST' , '꼬맹이','집에가자자자자'
);

SELECT *
FROM PRACTICE_BOARD
WHERE p_NUM = 1;

DELETE FROM PRACTICE_BOARD
WHERE p_NUM = 1;

UPDATE PRACTICE_BOARD
SET 
TITLE = '멍멍',
WRITER = '강아지',
CONTENT = '왈왈'
WHERE p_NUM = 3;score_info
