

SHOW CREATE TABLE products;


SELECT * FROM inventory;

SELECT * FROM orders ;

INSERT INTO order_requests(
	PRODUCT_NUM
	,CUSTOMER_NUM
	,QUANTITY

) VALUES(
	4
	,31
	,1000
),(
	5
	,31
	,5000
);


SELECT
  ORDER_NUM
  ,O.REQUEST_NUM
  ,ORDER_DATE
  ,ORDER_STATUS
  ,C.CUSTOMER_NUM
  ,C.CUSTOMER_NAME
  ,SUM((R.QUANTITY * P.PRODUCT_PRICE)) as TOTALPRICE
  ,P.PRODUCT_NUM
  ,SUM(QUANTITY) AS QUANTITY
  FROM order_requests R, orders O , customers C, products P, inventory I
  WHERE O.REQUEST_NUM = R.REQUEST_NUM
  AND R.CUSTOMER_NUM = C.CUSTOMER_NUM
  AND R.PRODUCT_NUM = P.PRODUCT_NUM
  AND P.PRODUCT_NUM = I.PRODUCT_NUM
  AND O.ORDER_STATUS = '배송대기'
  GROUP BY O.ORDER_DATE
  ORDER BY R.REQUEST_NUM DESC;


SELECT R.PRODUCT_NUM, SUM(QUANTITY) 
FROM orders O, order_requests R
WHERE O.REQUEST_NUM = R.REQUEST_NUM 
AND O.ORDER_STATUS = '배송대기'
GROUP BY R.PRODUCT_NUM;

SELECT I.PRODUCT_NUM, CURRENT_STOCK
FROM inventory I, order_requests R
WHERE I.PRODUCT_NUM = R.PRODUCT_NUM
GROUP BY I.PRODUCT_NUM;


SELECT R.PRODUCT_NUM, 
CASE 
	WHEN (I.CURRENT_STOCK - SUM(QUANTITY)) <  -1 THEN '!'
	ELSE '-' 
	END AS CHECK_STOCK 
FROM orders O, order_requests R , inventory I
WHERE O.REQUEST_NUM = R.REQUEST_NUM 
AND I.PRODUCT_NUM = R.PRODUCT_NUM
AND O.ORDER_STATUS = '배송대기'
GROUP BY R.PRODUCT_NUM;



SELECT 
    R.PRODUCT_NUM, 
    CASE 
        WHEN (CURRENT_STOCK - SUM(QUANTITY)) < -1
    END AS CHECK_STOCK
FROM orders O
JOIN order_requests R ON O.REQUEST_NUM = R.REQUEST_NUM
JOIN inventory I ON I.PRODUCT_NUM = R.PRODUCT_NUM
WHERE O.ORDER_STATUS = '배송대기'
GROUP BY R.PRODUCT_NUM;



-- 241022 그룹화 개개인

 SELECT C.CUSTOMER_NAME
        ,C.CUSTOMER_ADDR
        ,C.CUSTOMER_OWNER
        ,C.CUSTOMER_TEL
        ,O.ORDER_NUM
        ,O.ORDER_DATE
        ,P.PRODUCT_NAME
        ,R.PRODUCT_NUM
        ,R.QUANTITY
        , P.PRODUCT_PRICE
        ,(P.PRODUCT_PRICE * QUANTITY) AS PRODUCT_PRICE
        ,O.ORDER_STATUS
        FROM order_requests R , products P , orders O, customers C
        WHERE O.REQUEST_NUM = R.REQUEST_NUM
        AND C.CUSTOMER_NUM = R.CUSTOMER_NUM
        AND R.PRODUCT_NUM = P.PRODUCT_NUM
        AND O.ORDER_DATE = '2024-10-21 16:56:53'
		  AND O.ORDER_STATUS = '배송대기';


