-- 트리거를 사용하여 발주 테이블에 주문이 들어오면 수주테이블에 자동 저장
CREATE TRIGGER AFTER_INSERT_ORDER_REQUESTS
AFTER INSERT ON ORDER_REQUESTS
FOR EACH ROW
   INSERT INTO ORDERS (REQUEST_NUM, ORDER_STATUS, ORDER_DATE)
   VALUES (new.REQUEST_NUM, '배송대기', NOW());

	
-- 트리거 UPDATE 주문취소 (거래처>공급사)	
CREATE TRIGGER order_orderRequest_update	
	AFTER UPDATE
	ON ORDER_REQUESTS
	FOR EACH ROW
UPDATE orders	
SET ORDER_STATUS='주문취소'	
WHERE REQUEST_NUM=NEW.REQUEST_NUM	
AND NEW.REQUEST_STATUS='주문취소';	
