-- 트리거를 사용하여 발주 테이블에 주문이 들어오면 수주테이블에 자동 저장
CREATE TRIGGER AFTER_INSERT_ORDER_REQUESTS
AFTER INSERT ON ORDER_REQUESTS
FOR EACH ROW
   INSERT INTO ORDERS (REQUEST_NUM, ORDER_STATUS, ORDER_DATE)
   VALUES (new.REQUEST_NUM, '배송대기', NOW());


-- 수주 테이블의 order_status가 바꾸면 발주의 status도 바뀌도록
CREATE TRIGGER AFTER_UPDATE_ORDERS
AFTER UPDATE ON ORDERS
FOR EACH ROW
IF OLD.ORDER_STATUS != NEW.ORDER_STATUS THEN BEGIN
UPDATE order_requests
SET REQUEST_STATUS = NEW.ORDER_STATUS
WHERE REQUEST_NUM = NEW.REQUEST_NUM;


