
-- 240829

-- 테이블 DROP
DROP TABLE PATIENT_CHART;




SELECT * FROM medical_dept;
SELECT * FROM medical_doctor;
SELECT * FROM medical_member;
SELECT * FROM medical_schedule ORDER BY SCH_DATE DESC;
SELECT * FROM patient_chart;
SELECT * FROM DOCTOR_IMG;
SELECT * FROM user_board;
SELECT * FROM patient_chart;

-- 과거(오늘기준) 예약 삭제
DELETE FROM medical_schedule WHERE SCH_DATE < CURRENT_DATE();

DELETE FROM  medical_doctor WHERE doc_name = '다롱이';
-- --------------------------------------------------------------------

-- 2024-08-30
-- DROP TABLE medical_schedule;
-- DROP TABLE medical_doctor;
-- DROP TABLE medical_member;
-- DROP TABLE PATIENT_CHART;

CREATE TABLE medical_member(
  MEM_NUM VARCHAR(20) PRIMARY KEY
  ,MEM_NAME VARCHAR(20) NOT NULL
  ,MEM_TEL VARCHAR(50) NOT NULL UNIQUE
  ,MEM_RRN VARCHAR(20) UNIQUE NOT NULL
  ,MEM_ROLE VARCHAR(30) DEFAULT('USER')
);

-- 예약  예시를 멤버 인설트
INSERT INTO 


-- 20240830 의료진

CREATE TABLE MEDICAL_DOCTOR(
  DOC_NUM VARCHAR(20) PRIMARY KEY 
  ,DOC_NAME VARCHAR(20) NOT NULL
  ,DEPT_NUM INT  REFERENCES MEDICAL_DEPT(DEPT_NUM) ON DELETE CASCADE
  ,FOREIGN KEY (DOC_NUM) REFERENCES MEDICAL_MEMBER(MEM_NUM)        
);


CREATE TABLE MEDICAL_SCHEDULE(
        SCH_NUM INT PRIMARY KEY AUTO_INCREMENT -- 예약 번호(PK)
        ,DOC_NUM VARCHAR(20) REFERENCES medical_doctor(DOC_NUM) ON DELETE CASCADE -- 의료진 테이블 조인
        ,MEM_NUM VARCHAR(20) REFERENCES medical_member(MEM_NUM) ON DELETE CASCADE -- 환자 테이블 조인
        ,DEPT_NUM INT REFERENCES medical_dept(DEPT_NUM) ON DELETE CASCADE -- 진료과 테이블 조인
        ,REG_DATE DATETIME DEFAULT CURRENT_TIMESTAMP -- 접수날짜
        ,SCH_DATE DATE NOT NULL -- 예약 날짜 년월일
        ,SCH_TIME TIME NOT NULL -- 예약 날짜 시간
        ,DETAIL VARCHAR(100) -- 증상
        ,SCH_STATUS VARCHAR(10) DEFAULT('Y') -- 예약상태  
);


CREATE TABLE PATIENT_CHART(
	CHART_NUM INT AUTO_INCREMENT PRIMARY KEY
	,CHART_DATE DATETIME DEFAULT CURRENT_TIMESTAMP 
	,DOC_NUM VARCHAR(20) REFERENCES medical_doctor(DOC_NUM) ON DELETE CASCADE
   ,MEM_NUM VARCHAR(20) REFERENCES medical_member(MEM_NUM) ON DELETE CASCADE
   ,DEPT_NUM INT REFERENCES medical_dept(DEPT_NUM) ON DELETE CASCADE -- 진료과 번호 조인
	,SYMPTOM VARCHAR(200) NOT NULL -- 증상 
	,CHECK_UP VARCHAR(200) -- 검사
	,DISEASE VARCHAR(100) -- 병명
	,PRESCRIPTION VARCHAR(200) -- 처방
);

INSERT INTO patient_chart(
	DOC_NUM
	,MEM_NUM
	,DEPT_NUM
	,SYMPTOM
	,CHECK_UP
	,DISEASE
	,PRESCRIPTION
) VALUES(
	'DOC_00005'
	,'CTL_00001'
	,5
	,'가슴이 조여요'
	,'X-RAY'
	,'없음'
	,'OOO 7일분'
);


SELECT * FROM patient_chart WHERE MEM_NUM = 'CTL_00001';



INSERT INTO PATIENT_CHART(DOC_NUM, MEM_NUM, DEPT_NUM, SYMPTOM, CHECK_UP, DISEASE, PRESCRIPTION) 
VALUES(8,'11',2,'머리가 지끈','MRI검사','특별히 해당사항 없음','약 처방');

SELECT E.DEPT_NAME, D.DOC_NAME, M.MEM_NAME, M.MEM_NUM, M.MEM_RRN
FROM medical_member M , medical_dept E, medical_doctor D, medical_schedule S 
WHERE S.MEM_NUM = M.MEM_NUM
AND S.DEPT_NUM = D.DEPT_NUM 
AND S.DEPT_NUM = E.DEPT_NUM
AND S.MEM_NUM = 'CTL_00001'
AND S.DEPT_NUM = 4 ;

-- 진료차트 예약 환자를 누르면 예약 번호로 환자조회
SELECT E.DEPT_NAME, D.DOC_NAME, M.MEM_NAME, M.MEM_NUM, M.MEM_RRN
FROM medical_member M , medical_dept E, medical_doctor D, medical_schedule S 
WHERE S.MEM_NUM = M.MEM_NUM
AND S.DEPT_NUM = D.DEPT_NUM 
AND S.DEPT_NUM = E.DEPT_NUM
AND SCH_NUM = 1;


-- -------------------------------------------


INSERT INTO medical_dept(DEPT_NUM,DEPT_NAME) VALUES(1,'유방암');
INSERT INTO medical_dept(DEPT_NUM,DEPT_NAME) VALUES(2,'뇌종양');
INSERT INTO medical_dept(DEPT_NUM,DEPT_NAME) VALUES(3,'갑상선암');
INSERT INTO medical_dept(DEPT_NUM,DEPT_NAME) VALUES(4,'간암');
INSERT INTO medical_dept(DEPT_NUM,DEPT_NAME) VALUES(5,'폐암');
INSERT INTO medical_dept(DEPT_NUM,DEPT_NAME) VALUES(6,'혈액암');


SELECT DOC_NUM, DOC_NAME, D.DEPT_NUM , DEPT_NAME
        FROM  medical_doctor D, medical_dept T
        WHERE D.DEPT_NUM = T.DEPT_NUM
        ORDER BY DOC_NUM;


-- 이미지 테이블 생성

CREATE TABLE DOCTOR_IMG(
IMG_NUM INT PRIMARY KEY AUTO_INCREMENT
, ORIGIN_FILE_NAME VARCHAR(20)
, ATTACHED_FILE_NAME VARCHAR(20) NOT NULL
, DOC_NUM VARCHAR(20) REFERENCES medical_doctor(DOC_NUM)
);


-- 게시판 테이블

CREATE TABLE USER_BOARD(
BOARD_NUM INT AUTO_INCREMENT PRIMARY KEY
, TITLE VARCHAR(20)
, WRITER VARCHAR(10)
, CONTENT VARCHAR(1000)
, CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
, MEM_NUM VARCHAR(20) REFERENCES medical_member(MEM_NUM)
);


-- 환자 정보만

SELECT * FROM medical_member 
WHERE MEM_NUM LIKE '%CTL%' 
AND MEM_NAME LIKE '%유%';


