
-- 환자 정보
CREATE TABLE MEDICAL_MEMBER(
	MEM_NUM INT PRIMARY KEY AUTO_INCREMENT
	,MEM_NAME VARCHAR(20) NOT NULL
	,MEM_TEL VARCHAR(50) NOT NULL UNIQUE
	,MEM_RRN VARCHAR(20) UNIQUE NOT NULL
	,MEM_ROLE VARCHAR(30) DEFAULT('USER')
);mediclick

CREATE TABLE medical_dept(
	DEPT_NUM INT PRIMARY KEY AUTO_INCREMENT
	,DEPT_NAME VARCHAR(30) NOT NULL
);

-- 의료진
CREATE TABLE MEDICAL_DOCTOR(
	DOC_NUM INT PRIMARY KEY AUTO_INCREMENT
	,DOC_NAME VARCHAR(20) NOT NULL
	,DEPT_NUM INT REFERENCES MEDICAL_DEPT(DEPT_NUM) ON DELETE CASCADE
	
);

-- 예약(수정 전의 데이터)
CREATE TABLE MEDICAL_schedulE(
	SCH_NUM INT PRIMARY KEY AUTO_INCREMENT
	,DOC_NUM INT REFERENCES MEDICAL_DOCTOR(DOC_NUM) ON DELETE CASCADE
	,MEM_NUM INT REFERENCES MEDICAL_MEMBER(MEM_NUM) ON DELETE CASCADE
	,REG_DATE DATETIME DEFAULT CURRENT_TIMESTAMP -- 접수날짜
	,SCH_DATE DATETIME -- 예약날짜 건들일 예정
	,DETAIL VARCHAR(100)
	,SCH_STATUS VARCHAR(10) DEFAULT('Y')
);

-- ----------------------------------------------------------------------------------------------

SELECT * FROM medical_schedule;
SELECT * FROM medical_member;
SELECT * FROM medical_dept;
SELECT * FROM medical_doctor;

-- -----------------------------------------------------------------------------------------------

-- 테이블 DROP
-- DROP TABLE MEDICAL_SCHEDULE;



-- 예약이 겹치는지 확인하는 쿼리  제안 (20240826 )
SELECT  1 -- 2???
FROM Appointments
WHERE DOC_NUM = ?  -- 예약하려는 의사 ID
AND SCH_DATE = ?  -- 예약하려는 날짜
AND SCH_TIME = ?  -- 예약하려는 시간
LIMIT 1; -- 2?????


DELETE FROM medical_schedule;