
DROP TABLE temp_date;

CREATE TABLE temp_data (
	TEMP_NUM INT AUTO_INCREMENT PRIMARY KEY,
	CURRENT_TEMP DOUBLE,
	TEMP_TIME DATETIME DEFAULT CURRENT_TIMESTAMP()
);

SELECT * FROM temp_data
ORDER BY TEMP_TIME DESC;