

-- 환자 정보
CREATE TABLE MEDICAL_MEMBER(
	MEM_NUM INT PRIMARY KEY AUTO_INCREMENT
	,MEM_NAME VARCHAR(20) NOT NULL
	,MEM_TEL VARCHAR(50) NOT NULL UNIQUE
	,MEM_RRN VARCHAR(20) UNIQUE NOT NULL
	,MEM_ROLE VARCHAR(30) DEFAULT('USER')
);


DROP TABLE medical_dept;
DROP TABLE medical_doctor;
DROP TABLE medical_schedule;

CREATE TABLE medical_dept(
	DEPT_NUM INT PRIMARY KEY AUTO_INCREMENT
	,DEPT_NAME VARCHAR(30) NOT NULL
	
);

-- 의료진
CREATE TABLE MEDICAL_DOCTOR(
	DOC_NUM INT PRIMARY KEY AUTO_INCREMENT
	,DOC_NAME VARCHAR(20) NOT NULL
	,DEPT_NUM INT REFERENCES MEDICAL_DEPT(DEPT_NUM) ON DELETE CASCADE
	
);

-- 예약
CREATE TABLE MEDICAL_schedulE(
	SCH_NUM INT PRIMARY KEY AUTO_INCREMENT
	,DOC_NUM INT REFERENCES MEDICAL_DOCTOR(DOC_NUM) ON DELETE CASCADE
	,MEM_NUM INT REFERENCES MEDICAL_MEMBER(MEM_NUM) ON DELETE CASCADE
	,REG_DATE DATETIME DEFAULT CURRENT_TIMESTAMP -- 접수날짜
	,SCH_DATE DATETIME -- 예약날짜 건들일 예정
	,DETAIL VARCHAR(100)
	,SCH_STATUS VARCHAR(10) DEFAULT('Y')
);


UPDATE medical_doctor
SET DOC_NAME = '정다영'
WHERE DOC_NUM = 12;
